title: Lovell D&#039;souza &ndash; Freelance Photographer, Web Developer, Traveler.
email: lovelldies@gmail.com
description: The glorious website of Lovell D&#039;souza. Showcasing photography from weddings and travel, web development and other random matter that may amuse you.
image: https://farm1.staticflickr.com/598/32762787495_c0bff8968d_h.jpg
baseurl: "/lovelldsouza" # the subpath of your site, e.g. /blog
url: "https://api-project-496539557864.firebaseapp.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lovelldies
github_username:  lovelldies
permalink: /:categories/:title/
markdown: redcarpet
preloadimage: https://happyfeet.us/assets/img/loading.gif
exclude: [ 'ignore', '.vscode', '.gitignore', 'drafts' ] 