title: Lovell D&#039;souza &ndash; Freelance Photographer, Web Developer, Traveler.
email: lovelldies@gmail.com
description: The glorious website of Lovell D&#039;souza. Showcasing photography from weddings and travel, web development and other random matter that may amuse you.
image: https://c2.staticflickr.com/4/3817/33774023415_4fe4bf7709_b.jpg
baseurl: "/lovelldsouza" # the subpath of your site, e.g. /blog
url: "https://api-project-496539557864.firebaseapp.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lovelldies
github_username:  lovelldies
permalink: /:categories/:title/
markdown: redcarpet
preloadimage: https://happyfeet.us/assets/img/loading.gif
exclude: [ 'ignore', '.vscode', '.gitignore', 'drafts' ] 